USE DB_DONALABWEB
GO


INSERT INTO MAESTRO.PARAMETRO (	PARA_GRUPO, PARA_ORDEN,PARA_VALOR,
								PARA_ACTIVO,PARA_USUARIO_CREACION,
								PARA_FECHA_CREACION,PARA_IP_CREACION)
SELECT UPPER(Maestro),ISNULL(Orden, 0),UPPER(Detalle),1,1,GETDATE(),'0.0.0.0' FROM DB_SABS.[dbo].[T_MaestroDetalle]


--SELECT * FROM MAESTRO.PARAMETRO

--DELETE FROM MAESTRO.PARAMETRO



