USE DB_DONALABWEB
GO

-- Crear esquema SEGURIDAD si no existe
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SEGURIDAD')
BEGIN
    EXEC('CREATE SCHEMA SEGURIDAD');
END;

-- Tabla ENTIDAD
CREATE TABLE SEGURIDAD.ENTIDAD (
    ENTI_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    ENTI_PAIS BIGINT NULL,
    ENTI_RAZON_SOCIAL VARCHAR(150) NOT NULL,
    ENTI_IDENTIFICACION_TIPO VARCHAR(10) NULL,
    ENTI_IDENTIFICACION_NUMERO VARCHAR(50) NULL,
    ENTI_ACTIVO BIT NOT NULL DEFAULT 1,
    ENTI_USUARIO_CREACION BIGINT NULL,
    ENTI_FECHA_CREACION DATETIME NOT NULL,
    ENTI_IP_CREACION VARCHAR(20) NOT NULL,
    ENTI_USUARIO_MODIFICACION BIGINT NULL,
    ENTI_FECHA_MODIFICACION DATETIME NULL,
    ENTI_IP_MODIFICACION VARCHAR(20) NULL,
    --FOREIGN KEY (ENTI_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    --FOREIGN KEY (ENTI_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);

-- Tabla USUARIO
CREATE TABLE SEGURIDAD.USUARIO (
    USUA_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USUA_ENTIDAD_ID BIGINT NOT NULL,
    USUA_ALIAS VARCHAR(20) NOT NULL,
    USUA_PASSWORD NVARCHAR(1000) NOT NULL,
    USUA_NOMBRES VARCHAR(100) NOT NULL,
    USUA_PRIMER_APELLIDO VARCHAR(100) NOT NULL,
    USUA_SEGUNDO_APELLIDO VARCHAR(100),
    USUA_DOC_IDENTIFICACION BIGINT NULL,
    USUA_DOC_IDENTIFICACION_NUMERO VARCHAR(50) NULL,
    USUA_CORREO VARCHAR(50) NULL,
    USUA_TELEFONO VARCHAR(20) NULL,
    USUA_MOVIL VARCHAR(20) NULL,
    USUA_ACTIVO BIT NOT NULL DEFAULT 1,
    USUA_USUARIO_CREACION BIGINT NULL,
    USUA_FECHA_CREACION DATETIME NOT NULL,
    USUA_IP_CREACION VARCHAR(20) NOT NULL,
    USUA_USUARIO_MODIFICACION BIGINT NULL,
    USUA_FECHA_MODIFICACION DATETIME NULL,
    USUA_IP_MODIFICACION VARCHAR(20) NULL,
    --FOREIGN KEY (USUA_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    --FOREIGN KEY (USUA_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);

INSERT INTO SEGURIDAD.ENTIDAD(ENTI_RAZON_SOCIAL, ENTI_FECHA_CREACION, ENTI_IP_CREACION)
VALUES ('SISTEMAS ANALÍTICOS',GETDATE(),'0.0.0.0');

INSERT INTO SEGURIDAD.USUARIO(	USUA_ENTIDAD_ID, USUA_ALIAS, USUA_PASSWORD, USUA_NOMBRES, USUA_PRIMER_APELLIDO, USUA_SEGUNDO_APELLIDO,
								USUA_FECHA_CREACION, USUA_IP_CREACION)
VALUES((SELECT ENTI_ID FROM SEGURIDAD.ENTIDAD WHERE ENTI_RAZON_SOCIAL = 'SISTEMAS ANALÍTICOS'), 'LNUNJA', 'MANUEL', 'NUNJA', 'ASTACIO', GETDATE(), '0.0.0.0')

