USE DB_DONALABWEB
GO

--SELECT * FROM SEGURIDAD.ENTIDAD
--SELECT * FROM SEGURIDAD.USUARIO
--SELECT * FROM MAESTRO.CONTINENTE
--SELECT * FROM MAESTRO.PAIS
--SELECT * FROM MAESTRO.PARAMETRO


/*
SELECT * FROM MAESTRO.CONTINENTE
SELECT STUFF((SELECT '|' + CAST(CONT_ID AS VARCHAR) FROM MAESTRO.CONTINENTE WHERE CONT_ACTIVO IN (0) FOR XML PATH('')), 1, 1, '')
*/

/*
DROP TABLE SEGURIDAD.USUARIO_CONFIGURACION
DROP TABLE SEGURIDAD.USUARIO_PERFIL
DROP TABLE SEGURIDAD.OPCION
DROP TABLE SEGURIDAD.FORMULARIO
DROP TABLE SEGURIDAD.PERFIL

DELETE FROM SEGURIDAD.USUARIO_CONFIGURACION
DELETE FROM SEGURIDAD.USUARIO_PERFIL
DELETE FROM SEGURIDAD.OPCION
DELETE FROM SEGURIDAD.FORMULARIO
DELETE FROM SEGURIDAD.PERFIL


*/

/*
SELECT * FROM SEGURIDAD.USUARIO_PERFIL
SELECT * FROM SEGURIDAD.USUARIO_CONFIGURACION
SELECT * FROM SEGURIDAD.FORMULARIO
SELECT * FROM SEGURIDAD.OPCION
SELECT * FROM SEGURIDAD.PERFIL
*/

DECLARE 
@USUARIO_ID BIGINT = (SELECT USUA_ID FROM SEGURIDAD.USUARIO WHERE USUA_ALIAS = 'LNUNJA')

SELECT	CONCAT(USUARIO.USUA_NOMBRES,' ',USUARIO.USUA_PRIMER_APELLIDO,' ',USUARIO.USUA_SEGUNDO_APELLIDO) AS USUARIO,
		USUARIO.USUA_ALIAS AS ALIAS,
		PERFIL.PERF_NOMBRE AS PERFIL,
		ENTIDAD.ENTI_RAZON_SOCIAL AS ENTIDAD
FROM SEGURIDAD.USUARIO_PERFIL USUARIO_PERFIL
INNER JOIN SEGURIDAD.USUARIO USUARIO ON USUARIO_PERFIL.USPE_USUARIO_ID = USUARIO.USUA_ID
INNER JOIN SEGURIDAD.ENTIDAD ENTIDAD ON USUARIO.USUA_ENTIDAD_ID = ENTIDAD.ENTI_ID
INNER JOIN SEGURIDAD.PERFIL PERFIL ON USUARIO_PERFIL.USPE_PERFIL_ID = PERFIL.PERF_ID
WHERE USUARIO_PERFIL.USPE_USUARIO_ID = @USUARIO_ID

SELECT	FORMULARIO.FORM_ID AS ID,
		FORMULARIO.FORM_NOMBRE AS FORMULARIO,
		FORMULARIO.FORM_RUTA AS RUTA,
		FORMULARIO.FORM_DEPENDENCIA AS DEPENDENCIA
FROM SEGURIDAD.USUARIO_PERFIL USUARIO_PERFIL
INNER JOIN SEGURIDAD.USUARIO_CONFIGURACION CONFIG ON USUARIO_PERFIL.USPE_ID = CONFIG.USCO_USUARIO_PERFIL_ID
INNER JOIN SEGURIDAD.FORMULARIO FORMULARIO ON CONFIG.USCO_FORMULARIO_ID = FORMULARIO.FORM_ID
WHERE USUARIO_PERFIL.USPE_USUARIO_ID = @USUARIO_ID
ORDER BY 1,4