USE DB_DONALABWEB
GO

-- Crear esquema SEGURIDAD si no existe
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SEGURIDAD')
BEGIN
    EXEC('CREATE SCHEMA SEGURIDAD');
END;

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SEGURIDAD.PERFIL') AND type = 'U')
	BEGIN
		-- Tabla PERFIL
		CREATE TABLE SEGURIDAD.PERFIL (
			PERF_ID BIGINT PRIMARY KEY IDENTITY(1,1),
			PERF_ENTIDAD_ID BIGINT NOT NULL,
			PERF_NOMBRE VARCHAR(50) NOT NULL,
			PERF_ACTIVO BIT NOT NULL DEFAULT 1,
			PERF_USUARIO_CREACION BIGINT NOT NULL,
			PERF_FECHA_CREACION DATETIME NOT NULL,
			PERF_IP_CREACION VARCHAR(20) NOT NULL,
			PERF_USUARIO_MODIFICACION BIGINT NULL,
			PERF_FECHA_MODIFICACION DATETIME NULL,
			PERF_IP_MODIFICACION VARCHAR(20) NULL,
			FOREIGN KEY (PERF_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (PERF_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
		);
	END
ELSE
BEGIN
    PRINT 'La tabla SEGURIDAD.PERFIL ya existe.';
END

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SEGURIDAD.FORMULARIO') AND type = 'U')
	BEGIN
		-- Tabla FORMULARIO
		CREATE TABLE SEGURIDAD.FORMULARIO (
			FORM_ID BIGINT PRIMARY KEY IDENTITY(1,1),
			FORM_NOMBRE VARCHAR(50) NOT NULL,
			FORM_RUTA VARCHAR(200) NULL DEFAULT NULL,
			FORM_DEPENDENCIA BIGINT NULL DEFAULT 0,
			FORM_ACTIVO BIT NOT NULL DEFAULT 1,
			FORM_USUARIO_CREACION BIGINT NOT NULL,
			FORM_FECHA_CREACION DATETIME NOT NULL,
			FORM_IP_CREACION VARCHAR(20) NOT NULL,
			FORM_USUARIO_MODIFICACION BIGINT NULL,
			FORM_FECHA_MODIFICACION DATETIME NULL,
			FORM_IP_MODIFICACION VARCHAR(20) NULL,
			FOREIGN KEY (FORM_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (FORM_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
		);
	END
ELSE
BEGIN
    PRINT 'La tabla SEGURIDAD.FORMULARIO ya existe.';
END

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SEGURIDAD.OPCION') AND type = 'U')
	BEGIN
		-- Tabla OPCION
		CREATE TABLE SEGURIDAD.OPCION (
			OPCI_ID BIGINT PRIMARY KEY IDENTITY(1,1),
			OPCI_FORMULARIO_ID BIGINT NOT NULL,
			OPCI_NOMBRE VARCHAR(50) NOT NULL,
			OPCI_ACTIVO BIT NOT NULL DEFAULT 1,
			OPCI_USUARIO_CREACION BIGINT NOT NULL,
			OPCI_FECHA_CREACION DATETIME NOT NULL,
			OPCI_IP_CREACION VARCHAR(20) NOT NULL,
			OPCI_USUARIO_MODIFICACION BIGINT NULL,
			OPCI_FECHA_MODIFICACION DATETIME NULL,
			OPCI_IP_MODIFICACION VARCHAR(20) NULL,
			FOREIGN KEY (OPCI_FORMULARIO_ID) REFERENCES SEGURIDAD.FORMULARIO(FORM_ID),
			FOREIGN KEY (OPCI_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (OPCI_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
		);
	END
ELSE
BEGIN
    PRINT 'La tabla SEGURIDAD.OPCION ya existe.';
END

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SEGURIDAD.USUARIO_PERFIL') AND type = 'U')
	BEGIN
		-- Tabla USUARIO_PERFIL
		CREATE TABLE SEGURIDAD.USUARIO_PERFIL (
			USPE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
			USPE_USUARIO_ID BIGINT,
			USPE_PERFIL_ID BIGINT,
			USPE_ACTIVO BIT DEFAULT 1,
			USPE_USUARIO_CREACION BIGINT,
			USPE_FECHA_CREACION DATETIME,
			USPE_IP_CREACION VARCHAR(20),
			USPE_USUARIO_MODIFICACION BIGINT,
			USPE_FECHA_MODIFICACION DATETIME,
			USPE_IP_MODIFICACION VARCHAR(20),
			FOREIGN KEY (USPE_USUARIO_ID) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (USPE_PERFIL_ID) REFERENCES SEGURIDAD.PERFIL(PERF_ID),
			FOREIGN KEY (USPE_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (USPE_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
		);
	END
ELSE
BEGIN
    PRINT 'La tabla SEGURIDAD.USUARIO_PERFIL ya existe.';
END

IF NOT EXISTS (SELECT 1 FROM sys.objects WHERE object_id = OBJECT_ID(N'SEGURIDAD.USUARIO_CONFIGURACION') AND type = 'U')
	BEGIN
		-- Tabla USUARIO_CONFIGURACION
		CREATE TABLE SEGURIDAD.USUARIO_CONFIGURACION (
			USCO_ID BIGINT PRIMARY KEY IDENTITY(1,1),
			USCO_USUARIO_PERFIL_ID BIGINT,
			USCO_FORMULARIO_ID BIGINT,
			USCO_OPCION VARCHAR(200),
			USCO_ACTIVO BIT DEFAULT 1,
			USCO_USUARIO_CREACION BIGINT,
			USCO_FECHA_CREACION DATETIME,
			USCO_IP_CREACION VARCHAR(20),
			USCO_USUARIO_MODIFICACION BIGINT,
			USCO_FECHA_MODIFICACION DATETIME,
			USCO_IP_MODIFICACION VARCHAR(20),
			FOREIGN KEY (USCO_USUARIO_PERFIL_ID) REFERENCES SEGURIDAD.USUARIO_PERFIL(USPE_ID),
			FOREIGN KEY (USCO_FORMULARIO_ID) REFERENCES SEGURIDAD.FORMULARIO(FORM_ID),
			FOREIGN KEY (USCO_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
			FOREIGN KEY (USCO_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
		);
	END
ELSE
BEGIN
    PRINT 'La tabla SEGURIDAD.USUARIO_CONFIGURACION ya existe.';
END

DECLARE
@USUARIO_ID BIGINT = (SELECT USUA_ID FROM SEGURIDAD.USUARIO WHERE USUA_ALIAS = 'LNUNJA'),
@PERFIL_ADMINISTRADOR BIGINT,
@GESTION BIGINT,
@GESTION_CAMPANIA BIGINT,
@GESTION_CAMPANIA_LISTA BIGINT,
@GESTION_CAMPANIA_RESERVAR BIGINT,
@GESTION_CAMPANIA_ASIGNAR BIGINT,
@GESTION_DONACION BIGINT,
@GESTION_DONACION_POSTULANTE BIGINT,
@GESTION_REPORTES BIGINT,
@GESTION_REPORTES_ESTADISTICA BIGINT,
@GESTION_REPORTES_GENERADOR BIGINT,
@LABORATORIO BIGINT,
@LABORATORIO_UNIDADES BIGINT,

@USUARIO_PERFIL BIGINT,
@USUARIO_CONFFIGURACION BIGINT

-- CREAR PERFIL
INSERT INTO SEGURIDAD.PERFIL(PERF_ENTIDAD_ID, PERF_NOMBRE, PERF_USUARIO_CREACION, PERF_FECHA_CREACION, PERF_IP_CREACION)
VALUES ((SELECT ENTI_ID FROM SEGURIDAD.ENTIDAD WHERE ENTI_RAZON_SOCIAL = 'SISTEMAS ANALÍTICOS'),'ADMINISTRADOR', @USUARIO_ID, GETDATE(), '0.0.0.0');

SET @PERFIL_ADMINISTRADOR = @@IDENTITY

-- CREAR FORMULARIO NIVEL 1
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('GESTION', @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION = @@IDENTITY

-- CREAR FORMULARIO NIVEL 2
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('CAMPAÑA', @GESTION, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_CAMPANIA = @@IDENTITY

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('LISTA', '/[ruta form]', @GESTION_CAMPANIA, @USUARIO_ID,GETDATE(), '0.0.0.0')
SET @GESTION_CAMPANIA_LISTA = @@IDENTITY
-- CREAR OPCION DE FORMULARIO
INSERT INTO SEGURIDAD.OPCION(OPCI_FORMULARIO_ID,OPCI_NOMBRE,OPCI_USUARIO_CREACION,OPCI_FECHA_CREACION,OPCI_IP_CREACION)
VALUES
(@GESTION_CAMPANIA_LISTA,'buscar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_LISTA,'nuevo',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_LISTA,'editar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_LISTA,'eliminar',@USUARIO_ID,GETDATE(),'0.0.0.0')

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('RESERVAR CODIGOS', '/[ruta form]', @GESTION_CAMPANIA, @USUARIO_ID,GETDATE(), '0.0.0.0')
SET @GESTION_CAMPANIA_RESERVAR = @@IDENTITY
-- CREAR OPCION DE FORMULARIO
INSERT INTO SEGURIDAD.OPCION(OPCI_FORMULARIO_ID,OPCI_NOMBRE,OPCI_USUARIO_CREACION,OPCI_FECHA_CREACION,OPCI_IP_CREACION)
VALUES(@GESTION_CAMPANIA_RESERVAR,'generar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_RESERVAR,'editar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_RESERVAR,'eliminar',@USUARIO_ID,GETDATE(),'0.0.0.0')

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('ASIGNAR CODIGOS', '/[ruta form]', @GESTION_CAMPANIA, @USUARIO_ID,GETDATE(), '0.0.0.0')
SET @GESTION_CAMPANIA_ASIGNAR = @@IDENTITY
-- CREAR OPCION DE FORMULARIO
INSERT INTO SEGURIDAD.OPCION(OPCI_FORMULARIO_ID,OPCI_NOMBRE,OPCI_USUARIO_CREACION,OPCI_FECHA_CREACION,OPCI_IP_CREACION)
VALUES(@GESTION_CAMPANIA_ASIGNAR,'asignar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_ASIGNAR,'editar',@USUARIO_ID,GETDATE(),'0.0.0.0'),
(@GESTION_CAMPANIA_ASIGNAR,'eliminar',@USUARIO_ID,GETDATE(),'0.0.0.0')

-- CREAR FORMULARIO NIVEL 2
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('DONACION', @GESTION, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_DONACION = @@IDENTITY

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('POSTULANTE', '/[ruta form]', @GESTION_DONACION, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_DONACION_POSTULANTE = @@IDENTITY

-- CREAR FORMULARIO NIVEL 2
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('REPORTES', @GESTION, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_REPORTES = @@IDENTITY

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('ESTADISTICA', '/[ruta form]', @GESTION_REPORTES, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_REPORTES_ESTADISTICA = @@IDENTITY

-- CREAR FORMULARIO NIVEL 3
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_RUTA, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('GENERADOR DE REPORTES', '/[ruta form]', @GESTION_REPORTES, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @GESTION_REPORTES_GENERADOR = @@IDENTITY

-- CREAR FORMULARIO NIVEL 1
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('LABORATORIO', @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @LABORATORIO = @@IDENTITY

-- CREAR FORMULARIO NIVEL 2
INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_DEPENDENCIA, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('UNIDADES', @LABORATORIO, @USUARIO_ID,GETDATE(), '0.0.0.0')

SET @LABORATORIO_UNIDADES = @@IDENTITY

-- ASIGAN EL PERFIL AL USUARIO
INSERT INTO SEGURIDAD.USUARIO_PERFIL(USPE_USUARIO_ID, USPE_PERFIL_ID, USPE_USUARIO_CREACION, USPE_FECHA_CREACION, USPE_IP_CREACION)
VALUES (@USUARIO_ID, @PERFIL_ADMINISTRADOR,@USUARIO_ID,GETDATE(),'0.0.0.0')

SET @USUARIO_PERFIL = @@IDENTITY

-- ASIGNA FORMULARIOS Y SUS OPCIONES AL PERFIL DE USUARIO
INSERT INTO SEGURIDAD.USUARIO_CONFIGURACION(USCO_USUARIO_PERFIL_ID, USCO_FORMULARIO_ID, USCO_OPCION, USCO_USUARIO_CREACION, USCO_FECHA_CREACION, USCO_IP_CREACION)
VALUES
(@USUARIO_PERFIL, @GESTION, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_CAMPANIA, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_CAMPANIA_LISTA, (SELECT STUFF((SELECT '|' + CAST(OPCI_ID AS VARCHAR) FROM SEGURIDAD.OPCION WHERE OPCI_FORMULARIO_ID=@GESTION_CAMPANIA_LISTA FOR XML PATH('')), 1, 1, '')), @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_CAMPANIA_RESERVAR, (SELECT STUFF((SELECT '|' + CAST(OPCI_ID AS VARCHAR) FROM SEGURIDAD.OPCION WHERE OPCI_FORMULARIO_ID=@GESTION_CAMPANIA_RESERVAR FOR XML PATH('')), 1, 1, '')), @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_CAMPANIA_ASIGNAR, (SELECT STUFF((SELECT '|' + CAST(OPCI_ID AS VARCHAR) FROM SEGURIDAD.OPCION WHERE OPCI_FORMULARIO_ID=@GESTION_CAMPANIA_ASIGNAR FOR XML PATH('')), 1, 1, '')), @USUARIO_ID, GETDATE(), '0.0.0.0'),

(@USUARIO_PERFIL, @GESTION_DONACION, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_DONACION_POSTULANTE, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),

(@USUARIO_PERFIL, @GESTION_REPORTES, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_REPORTES_ESTADISTICA, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @GESTION_REPORTES_GENERADOR, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),

(@USUARIO_PERFIL, @LABORATORIO, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0'),
(@USUARIO_PERFIL, @LABORATORIO_UNIDADES, NULL, @USUARIO_ID, GETDATE(), '0.0.0.0')

