USE DB_DONALABWEB
GO

-- Crear esquema SEGURIDAD si no existe
IF NOT EXISTS (SELECT * FROM sys.schemas WHERE name = 'SEGURIDAD')
BEGIN
    EXEC('CREATE SCHEMA SEGURIDAD');
END;

-- Tabla PERFIL
CREATE TABLE SEGURIDAD.PERFIL (
    PERF_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    PERF_ENTIDAD_ID BIGINT NOT NULL,
    PERF_NOMBRE VARCHAR(50) NOT NULL,
    PERF_ACTIVO BIT NOT NULL DEFAULT 1,
    PERF_USUARIO_CREACION BIGINT NOT NULL,
    PERF_FECHA_CREACION DATETIME NOT NULL,
    PERF_IP_CREACION VARCHAR(20) NOT NULL,
    PERF_USUARIO_MODIFICACION BIGINT NULL,
    PERF_FECHA_MODIFICACION DATETIME NULL,
    PERF_IP_MODIFICACION VARCHAR(20) NULL,
    FOREIGN KEY (PERF_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (PERF_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);

-- Tabla FORMULARIO
CREATE TABLE SEGURIDAD.FORMULARIO (
    FORM_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    FORM_NOMBRE VARCHAR(50) NOT NULL,
	FORM_RUTA VARCHAR(200) NULL,
	FORM_DEPENDENCIA BIGINT NULL,
    FORM_ACTIVO BIT NOT NULL DEFAULT 1,
    FORM_USUARIO_CREACION BIGINT NOT NULL,
    FORM_FECHA_CREACION DATETIME NOT NULL,
    FORM_IP_CREACION VARCHAR(20) NOT NULL,
    FORM_USUARIO_MODIFICACION BIGINT NULL,
    FORM_FECHA_MODIFICACION DATETIME NULL,
    FORM_IP_MODIFICACION VARCHAR(20) NULL,
    FOREIGN KEY (FORM_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (FORM_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);

-- Tabla OPCION
CREATE TABLE SEGURIDAD.OPCION (
    OPCI_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    OPCI_FORMULARIO_ID BIGINT NOT NULL,
    OPCI_NOMBRE VARCHAR(50) NOT NULL,
    OPCI_ACTIVO BIT NOT NULL,
    OPCI_USUARIO_CREACION BIGINT NOT NULL,
    OPCI_FECHA_CREACION DATETIME NOT NULL,
    OPCI_IP_CREACION VARCHAR(20) NOT NULL,
    OPCI_USUARIO_MODIFICACION BIGINT NULL,
    OPCI_FECHA_MODIFICACION DATETIME NULL,
    OPCI_IP_MODIFICACION VARCHAR(20) NULL,
    FOREIGN KEY (OPCI_FORMULARIO_ID) REFERENCES SEGURIDAD.FORMULARIO(FORM_ID),
    FOREIGN KEY (OPCI_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (OPCI_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);

-- Tabla USUARIO_CONFIGURACION
CREATE TABLE SEGURIDAD.USUARIO_PERFIL (
    USPE_ID BIGINT PRIMARY KEY IDENTITY(1,1),
    USPE_USUARIO_ID BIGINT,
    USPE_PERFIL_ID VARCHAR(200),
    USPE_ACTIVO BIT,
    USPE_USUARIO_CREACION BIGINT,
    USPE_FECHA_CREACION DATETIME,
    USPE_IP_CREACION VARCHAR(20),
    USPE_USUARIO_MODIFICACION BIGINT,
    USPE_FECHA_MODIFICACION DATETIME,
    USPE_IP_MODIFICACION VARCHAR(20),
    FOREIGN KEY (USPE_USUARIO_ID) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (USPE_PERFIL_ID) REFERENCES SEGURIDAD.PERFIL(PERF_ID),
    FOREIGN KEY (USPE_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (USPE_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);
-- Tabla USUARIO_CONFIGURACION
CREATE TABLE SEGURIDAD.USUARIO_CONFIGURACION (
    USCO_ID BIGINT PRIMARY KEY IDENTITY(1,1),
	USCO_USUARIO_PERFIL_ID BIGINT,
    USCO_FORMULARIO_ID BIGINT,
    USCO_OPCION VARCHAR(200),
    USCO_ACTIVO BIT,
    USCO_USUARIO_CREACION BIGINT,
    USCO_FECHA_CREACION DATETIME,
    USCO_IP_CREACION VARCHAR(20),
    USCO_USUARIO_MODIFICACION BIGINT,
    USCO_FECHA_MODIFICACION DATETIME,
    USCO_IP_MODIFICACION VARCHAR(20),
    FOREIGN KEY (USCO_USUARIO_PERFIL_ID) REFERENCES SEGURIDAD.USUARIO_PERFIL(USPE_ID),
    FOREIGN KEY (USCO_FORMULARIO_ID) REFERENCES SEGURIDAD.FORMULARIO(FORM_ID),
    FOREIGN KEY (USCO_USUARIO_CREACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID),
    FOREIGN KEY (USCO_USUARIO_MODIFICACION) REFERENCES SEGURIDAD.USUARIO(USUA_ID)
);


INSERT INTO SEGURIDAD.PERFIL(PERF_ENTIDAD_ID, PERF_NOMBRE, PERF_USUARIO_CREACION, PERF_FECHA_CREACION, PERF_IP_CREACION)
VALUES ((SELECT ENTI_ID FROM SEGURIDAD.ENTIDAD WHERE ENTI_RAZON_SOCIAL = 'SISTEMAS ANALÍTICOS'),'ADMINISTRADOR', (SELECT USUA_ID FROM SEGURIDAD.USUARIO WHERE USUA_ALIAS = 'LNUNJA'), GETDATE(), '0.0.0.0');

INSERT INTO SEGURIDAD.FORMULARIO(FORM_NOMBRE, FORM_USUARIO_CREACION, FORM_FECHA_CREACION, FORM_IP_CREACION)
VALUES('GESTION')

