USE [master]
GO

/****** Object:  Database [DB_DONALABWEB]    Script Date: 05/11/2024 12:14:47 ******/
CREATE DATABASE [DB_DONALABWEB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DB_DONALABWEB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_DONALABWEB.mdf' , SIZE = 5312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'DB_DONALABWEB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\DATA\DB_DONALABWEB_log.ldf' , SIZE = 11456KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [DB_DONALABWEB] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DB_DONALABWEB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DB_DONALABWEB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DB_DONALABWEB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DB_DONALABWEB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DB_DONALABWEB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DB_DONALABWEB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET RECOVERY FULL 
GO

ALTER DATABASE [DB_DONALABWEB] SET  MULTI_USER 
GO

ALTER DATABASE [DB_DONALABWEB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DB_DONALABWEB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DB_DONALABWEB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DB_DONALABWEB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DB_DONALABWEB] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DB_DONALABWEB] SET  READ_WRITE 
GO


